#!/bin/sh 
if [ $# != 1 ] ; then
echo "usage: if you want compile program file prog.s, just type command as:"
echo "./mak64 prog"
echo " '.s' is NOT necessay!"
exit 1;
fi 
filename=${1%.s}
echo ...compling $filename.s
#clear
#as   -gstabs -o $filename.o   $filename.s
 as  -g -o $filename.o   $filename.s
#ld -m elf_x86_64  -dynamic-linker /lib64/ld-linux.so.2 -lc  -o $filename $filename.o
#ld -m elf_x86_64  -dynamic-linking /lib/ld-linux.so.2 -lc  -o $filename $filename.o
ld  -dynamic-linker  /lib64/ld-linux-x86-64.so.2 -lc  -o $filename $filename.o
echo ...done!